baseURL = 'https://gjermund.tech/'
languageCode = 'en-us'
title = 'Gjermund'
theme = "hugo-theme-monochrome"
enableEmoji = true
paginate = 5

[params]
  description = "Gjermund's website. Cosmos blog and stuff."
  images = ['gjermundtechsocial.png']
  title = 'Gjermund'

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]
